# Automatically updated by the winget bot at 2021/Jan/21
Id: Heroku.HerokuCLI
Version: latest
Name: HerokuCLI
AppMoniker: heroku
Publisher: Heroku
License: ISC License
LicenseUrl: https://github.com/heroku/cli/blob/master/LICENSE
Description: The Heroku Command Line Interface (CLI) makes it easy to create and manage your Heroku apps directly from the terminal. It is an essential part of using Heroku.
Homepage: https://devcenter.heroku.com/articles/heroku-cli
Installers:
- Arch: x64
  Url: https://cli-assets.heroku.com/heroku-x64.exe
  Sha256: 1ca3f47bcb0094a4c8b2e6c92a15f431e563fc248cc4e317f30f4f52c1ad7f06
  InstallerType: nullsoft
