Id: MabelisYT.MabelTermSnap
Version: 1.4.3-Snap3
License: Copyright(c) 2019 - 2021 MabelisYT
Name: MabelTermSnap
AppMoniker: mabeltermsnap
Tags: "terminal, windows, utility"
Publisher: MabelisYT
Description: MabelisYT's Terminal Client For Windows 10, Snapshot Edition.
Installers:
    - Arch: x64
      Url: https://github.com/MabelYT/MabelTerm/releases/download/Snapshot/Update.exe
      InstallerType: Exe
      Sha256: F42ADD996C3668F9DCB0066E1C23AC552AA1288E044A94C3F93155ADE8280412
