# Automatically updated by the winget bot at 2021/Feb/11
Id: TopalaSoftwareSolutions.SIW
Publisher: Topala Software Solutions
Name: System Information for Windows
AppMoniker: siw
MinOSVersion: 6.1.0.0
Version: 2021.02.11.0
Description: System Information for Windows - Everything you want to know about your computer
License: Commercial
LicenseUrl: https://www.gtopala.com/agreement/
Homepage: https://www.gtopala.com/
Installers:
- Arch: Neutral
  Url: https://siw64.com/download/siwtrial-setup.exe
  Sha256: 644A77711732C91627354E22F46A9246D6FA3F9125F3CA850F4725015485BDB1
  InstallerType: Inno
  Switches:
    Silent: /VERYSILENT
    SilentWithProgress: /VERYSILENT
