# Automatically updated by the winget bot at 2021/Feb/13
Id: NimbusWeb.NimbusWeb
Name: NimbusWeb
AppMoniker: NimbusWeb
Version: 6.28.10
Publisher: NimbusWeb
License: Copyright (C) 2020 NimbusWeb
LicenseUrl: https://nimbusweb.me/terms-and-conditions.php
MinOSVersion: 10.0.0.0
Homepage: https://nimbusweb.me
Description: Transform information chaos from multiple sources into an organized workplace.
Tags: "nimbus web,nimbus note,"
Installers:
- Arch: x64
  Url: https://nimbusweb.me/nimbusnote.exe
  InstallerType: exe
  Sha256: 160C14FE3271F6CE6057A11DBC81FB4CFB2F0DF3A140CB644FEE0F462C1619E4
  Switches:
    Silent: /S
    SilentWithProgress: /S
